// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/v1/util.proto

package commonv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Common error.
type CommonError struct {
	// error code.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// error message.
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonError) Reset()         { *m = CommonError{} }
func (m *CommonError) String() string { return proto.CompactTextString(m) }
func (*CommonError) ProtoMessage()    {}
func (*CommonError) Descriptor() ([]byte, []int) {
	return fileDescriptor_a49dedceff6e7b32, []int{0}
}

func (m *CommonError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonError.Unmarshal(m, b)
}
func (m *CommonError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonError.Marshal(b, m, deterministic)
}
func (m *CommonError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonError.Merge(m, src)
}
func (m *CommonError) XXX_Size() int {
	return xxx_messageInfo_CommonError.Size(m)
}
func (m *CommonError) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonError.DiscardUnknown(m)
}

var xxx_messageInfo_CommonError proto.InternalMessageInfo

func (m *CommonError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommonError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonError)(nil), "common.v1.CommonError")
}

func init() { proto.RegisterFile("common/v1/util.proto", fileDescriptor_a49dedceff6e7b32) }

var fileDescriptor_a49dedceff6e7b32 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0x33, 0xd4, 0x2f, 0x2d, 0xc9, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x84, 0x88, 0xea, 0x95, 0x19, 0x2a, 0x19, 0x73, 0x71, 0x3b, 0x83, 0x39, 0xae, 0x45,
	0x45, 0xf9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0xac, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0xba, 0x04, 0x93, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x88, 0xe9, 0xe4, 0xca, 0xa5, 0x90, 0x9c, 0x9f, 0xab, 0x97, 0x58, 0x50, 0x5c, 0x9c,
	0x5f, 0x5a, 0x95, 0xa8, 0x97, 0x94, 0x9f, 0x9f, 0x5d, 0x5c, 0x92, 0x5f, 0x94, 0xaa, 0x07, 0x37,
	0xd8, 0x09, 0x6a, 0x6c, 0x00, 0xc8, 0xc2, 0x00, 0xc6, 0x28, 0x21, 0xb8, 0x43, 0xac, 0x21, 0xac,
	0x32, 0xc3, 0x24, 0x36, 0xb0, 0x6b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x07, 0x81,
	0x4b, 0xa5, 0x00, 0x00, 0x00,
}
